version: '3'

services:
  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
  
  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - user-service
